version: '3.3'
services:
  ft-db:
    image: mysql:5.7
    container_name: ft-db
    restart: always
    environment:
      MYSQL_DATABASE: 'ft-db'
      MYSQL_USER: 'pkuszneruk'
      MYSQL_PASSWORD: 'p@VII&t6D;^24089=N3+Bf6kn=QqE;dg'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - ft-network
  feynman-technique-backend:
    container_name: feynman-technique-backend
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
    - ft-db
    ports:
    - "5200:80"
    - "5400:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - ft-network
    volumes: 
      - db:/data
volumes:
  db:
networks:
    ft-network:
        external: true